# Generated by Django 4.2.1 on 2023-05-24 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='amount',
        ),
    ]
