# Generated by Django 4.2.1 on 2023-05-21 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cinemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinema',
            options={'verbose_name': 'кинотеатр', 'verbose_name_plural': 'кинотеатры'},
        ),
        migrations.AddField(
            model_name='cinema',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='cinemas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
